model_selection:
  model:
    XGBRegressor:
      n_estimators: 1500
      learning_rate: 0.05
      max_depth: 7
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
      objective: 'reg:squarederror'
      n_jobs: -1  